version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-dev
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql

volumes:
  mysql_data: